import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity=0.7
dynamic_title=true
padding = { x = 3, y = 3 }
dynamic_padding = true

[keyboard]
bindings = [
    {key = '+', mods='Control', action='IncreaseFontSize'},
    {key = '-', mods='Control', action='DecreaseFontSize'},
    {key = '0', mods='Control', action='ResetFontSize'},
    {key = "f", mods = "Control", chars = "~/tmux-sessionizer\n"}
]

[font]
size = 8.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"
family = "MesloLGM Nerd Font Mono"

